### ISSUE TITLE
your copying interstellar

### ISSUE THREAD

**Issue by Coding4Hours** [UltraN0va288/Cosmic#1]

**Comment by InchrysUploader** [comment]
HEY! I CARE!!!!!!

**Comment by InchrysUploader** [comment]
oh wait damn, its an exact copy

**Comment by UltraN0va288** [comment]
I used Interstellar as an inspiration but I tried to make it my own.

**Comment by Coding4Hours** [comment]
can you make it more different then

**Comment by theinfamouscoder5** [comment]
Yeah and you have to credit interstellar.

**Comment by theinfamouscoder5** [comment]
> I used Interstellar as an inspiration but I tried to make it my own.

Yeah but you aren't crediting them at all
