### ISSUE TITLE
Copy of Interstellar

### ISSUE THREAD

**Issue by theinfamouscoder5** [UltraN0va288/Cosmic#4]
Hey there, I'm Cody.

I just want to say that this is a clear import of Interstellar and you aren't crediting them in any way. All you did was add fancy rainbow borders and change the background image. If you are going to use Interstellar, you have to credit them. My friend's account got deleted because the didn't credit Interstellar and copied them.

Thanks,
Cody

**Comment by UltraN0va288** [comment]
Ok thanks I'll make sure to credit them. Thanks for bringing this to my attention

**Comment by theinfamouscoder5** [comment]
No problem, happy developing :)
